[package]
name = "can-ban"
version = "0.1.0"
edition = "2021"
description = "A tiny kanban board sample with rust and wasm"
authors = ["Burak Selim Åenyurt"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
