[package]
name = "feed-eater"
version = "0.1.0"
edition = "2021"
description = "Basit bir Feed reader uygulamasÄ±"

[dependencies]
feed-rs = "1.3.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
